# Generated by Django 5.0.14 on 2025-10-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='unique_identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('asset_type', 'unique_identifier')},
        ),
    ]
