# Generated by Django 5.0.14 on 2025-10-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_employee_options_employee_exit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assettype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
