# Generated by Django 5.2.17 on 2026-10-04 09:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def preflight_retired_linked_custody(apps, schema_editor):
    Asset = apps.get_model('assets', 'Asset')
    count = Asset.objects.using(schema_editor.connection.alias).filter(
        is_active=False, assigned_to__isnull=False,
    ).count()
    if count:
        raise RuntimeError(
            f'Custody migration stopped before schema changes: {count} retired asset(s) '
            'remain linked to holders. Review and resolve these historical rows '
            'with a separately approved, audited path before rerunning migrations.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assignment_history_global_asset_serial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(preflight_retired_linked_custody, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AssetExceptionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('recovery', 'Recovery pending'), ('missing', 'Reported missing'), ('inspection', 'Inspection hold')], max_length=12)),
                ('reason', models.TextField()),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('legacy', 'Legacy record'), ('staff', 'Staff action'), ('scheduled', 'Scheduled process')], max_length=12)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='disposition',
            field=models.CharField(choices=[('ready', 'Ready'), ('assigned', 'Assigned'), ('recovery_pending', 'Recovery pending'), ('missing', 'Reported missing'), ('inspection_hold', 'Inspection hold')], default='ready', max_length=20),
        ),
        migrations.AddField(
            model_name='assignmenthistory',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignmenthistory',
            name='observed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmenthistory',
            name='receipt_condition',
            field=models.CharField(blank=True, choices=[('usable', 'Usable'), ('damaged', 'Damaged')], max_length=8),
        ),
        migrations.AddField(
            model_name='assignmenthistory',
            name='source',
            field=models.CharField(choices=[('legacy', 'Legacy record'), ('staff', 'Staff action'), ('scheduled', 'Scheduled process')], default='legacy', max_length=12),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.employee'),
        ),
        migrations.AlterField(
            model_name='assignmenthistory',
            name='action',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('reassigned', 'Reassigned'), ('recovery_pending', 'Recovery pending'), ('missing_reported', 'Missing reported'), ('inspection_released', 'Inspection released')], max_length=24),
        ),
        migrations.AlterField(
            model_name='assignmenthistory',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_history', to='assets.employee'),
        ),
        migrations.AddField(
            model_name='assetexceptioncase',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exception_cases', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetexceptioncase',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_asset_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetexceptioncase',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_asset_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmenthistory',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='assets.assetexceptioncase'),
        ),
    ]
