# Generated by Django 5.2.17 on 2026-10-04 09:18

from django.db import migrations


def preserve_existing_custody(apps, schema_editor):
    Asset = apps.get_model('assets', 'Asset')
    Case = apps.get_model('assets', 'AssetExceptionCase')
    History = apps.get_model('assets', 'AssignmentHistory')
    alias = schema_editor.connection.alias
    Asset.objects.using(alias).filter(assigned_to__isnull=False).update(disposition='assigned')
    # A linked inactive holder is unresolved custody, never evidence of receipt.
    Asset.objects.using(alias).filter(
        is_active=True, assigned_to__isnull=False, assigned_to__is_active=False,
    ).update(disposition='recovery_pending')
    for asset_id, employee_id in Asset.objects.using(alias).filter(
            disposition='recovery_pending').values_list('pk', 'assigned_to_id').iterator():
        reason = 'Migration review: inactive holder remains linked; physical receipt is unverified.'
        case = Case.objects.using(alias).create(
            asset_id=asset_id, kind='recovery', reason=reason, source='legacy', observed_at=None,
        )
        History.objects.using(alias).create(
            asset_id=asset_id, employee_id=employee_id, action='recovery_pending',
            source='legacy', note=reason, case_id=case.pk, observed_at=None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_condition_aware_custody'),
    ]

    operations = [
        migrations.RunPython(preserve_existing_custody),
    ]
