# Generated by Django 5.2.17 on 2026-10-04 09:18

from django.conf import settings
from django.db import migrations, models


def hold_private_case_runtime_writes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql' or not settings.PRODUCTION:
        return
    # Keep the new private table readable by the paused web app. Write grants
    # are restored only at the separately reviewed cutover resume gate.
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT has_schema_privilege('assets_portfolio_app', 'assets_portfolio', 'USAGE')")
        if not cursor.fetchone()[0]:
            raise RuntimeError('The app role lacks USAGE on assets_portfolio; review role setup before migration.')
        cursor.execute('REVOKE ALL ON TABLE assets_portfolio.assets_assetexceptioncase FROM PUBLIC, anon, authenticated')
        cursor.execute('REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE assets_portfolio.assets_assetexceptioncase FROM assets_portfolio_app')
        cursor.execute('GRANT SELECT ON TABLE assets_portfolio.assets_assetexceptioncase TO assets_portfolio_app')
        cursor.execute("SELECT pg_get_serial_sequence('assets_portfolio.assets_assetexceptioncase', 'id')")
        sequence = cursor.fetchone()[0]
        if not sequence:
            raise RuntimeError('The new exception case identity sequence was not found.')
        # pg_get_serial_sequence returns the catalog-quoted identifier, and
        # the table and column names above are fixed by this migration.
        cursor.execute(f'REVOKE ALL ON SEQUENCE {sequence} FROM PUBLIC, anon, authenticated')
        cursor.execute(f'REVOKE USAGE, UPDATE ON SEQUENCE {sequence} FROM assets_portfolio_app')


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_backfill_custody_disposition'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(
                condition=(models.Q(disposition__in=['ready', 'inspection_hold'], assigned_to__isnull=True)
                           | models.Q(disposition__in=['assigned', 'recovery_pending', 'missing'], assigned_to__isnull=False)),
                name='asset_disposition_matches_holder',
            ),
        ),
        migrations.AddConstraint(
            model_name='assetexceptioncase',
            constraint=models.UniqueConstraint(
                fields=['asset'], condition=models.Q(resolved_at__isnull=True),
                name='one_open_exception_case_per_asset',
            ),
        ),
        migrations.AddConstraint(
            model_name='assetexceptioncase',
            constraint=models.CheckConstraint(
                condition=(models.Q(resolved_at__isnull=True, resolution_note='')
                           | (models.Q(resolved_at__isnull=False) & ~models.Q(resolution_note=''))),
                name='asset_case_resolution_note_required',
            ),
        ),
        migrations.RunPython(hold_private_case_runtime_writes, migrations.RunPython.noop),
    ]
